### PR TITLE
Merge 0.9.5

### PR DESCRIPTION
**Pull request by duckki**
Reviewing merge-0.9.5 branch

### CODE REVIEW

**Comment by duckki** [comment]
It's not efficient to review a merge commit on github.
I'm just using this PR for conversions.

Here're a few issues I found:
```diff
diff --git a/slither/slithir/convert.py b/slither/slithir/convert.py
index 7333e36b..6a34ceed 100644
--- a/slither/slithir/convert.py
+++ b/slither/slithir/convert.py
@@ -846,7 +846,7 @@ def propagate_types(ir: Operation, node: "Node"):  # pylint: disable=too-many-lo
                                 if v:
                                     ir.lvalue.set_type(v.type)
             elif isinstance(ir, NewArray):
-                ir.lvalue.set_type(ir.array_type)
+                ir.lvalue.set_type(ir.array_type) # lost our change?
             elif isinstance(ir, NewContract):
                 contract = node.file_scope.get_contract_from_name(ir.contract_name)
                 assert contract
diff --git a/slither/solc_parsing/expressions/expression_parsing.py b/slither/solc_parsing/expressions/expression_parsing.py
index b99b5e58..76ea37d7 100644
--- a/slither/solc_parsing/expressions/expression_parsing.py
+++ b/slither/solc_parsing/expressions/expression_parsing.py
@@ -471,7 +471,7 @@ def parse_expression(expression: Dict, caller_context: CallerContextExpression)
                 type_candidate = ElementaryType("string")
         elif type_candidate.startswith("rational_const "):
             type_candidate = ElementaryType("uint256")
-        elif type_candidate.startswith("int_const "):
+        elif type_candidate.startswith("int_const "): # Our fix seems lost.
             type_candidate = ElementaryType("uint256")
         elif type_candidate.startswith("bool"):
             type_candidate = ElementaryType("bool")
diff --git a/slither/visitors/expression/constants_folding.py b/slither/visitors/expression/constants_folding.py
index 81e09a3e..fbb44af5 100644
--- a/slither/visitors/expression/constants_folding.py
+++ b/slither/visitors/expression/constants_folding.py
@@ -285,6 +285,6 @@ class ConstantFolding(ExpressionVisitor):
         elif str(expression.type).startswith("byte") and isinstance(expr.value, int):
             value = int.to_bytes(expr.value, 32, "big")
         else:
-            print(f"!!! {expr.converted_value}")
+            print(f"!!! {expr.converted_value}") # TODO: remove
             value = convert_string_to_fraction(expr.converted_value)
         set_val(expression, value)
```

**Comment by duckki** [comment]
BTW, the latest slither-certik commit is `6c8d324fa`, but the merge-0.9.5 merged with `1f3ec498`, which 2 commits behind. We got to merge one more time with `6c8d324fa` or redo the merge.

Once that's done, create a companion PR in slither-task repo. I need to apply this patch:
```diff
diff --git a/slither-plugin/certik_slither_plugin/detectors/locked_ether.py b/slither-plugin/certik_slither_plugin/detectors/locked_ether.py
index 5b2385e..78b0196 100644
--- a/slither-plugin/certik_slither_plugin/detectors/locked_ether.py
+++ b/slither-plugin/certik_slither_plugin/detectors/locked_ether.py
@@ -15,7 +15,7 @@ from slither.slithir.operations import (
     LibraryCall,
     InternalCall,
 )
-from slither.slithir.operations.solidity_call import SolidityCustomRevert
+from slither.core.declarations.solidity_variables import SolidityCustomRevert
 from slither.utils.output import Output
```

When I ran the test suite, I saw one test was improved and these 4 tests were crashing: expensive-loop, sandwich-attack, flashloan-attack and unreachable-code.

The `unreachable-code` looked like SSA conversion failure.
For the other tests, we might need Pardis to look into them.

**Comment by kevinclancy** [comment]
For the change to `convert.py`, trail of bits [merged in a change](https://github.com/crytic/slither/pull/1784/files) that makes the `array_type` field of `NewArray` refer to the type of the array rather than the type of its elements. Therefore our fix is now out of date.

**Comment by kevinclancy** [comment]
For the `int_const` issue, `rational_const` has a space as well. I went ahead and removed that.

**Comment by duckki** [comment]
Initial merge's done. If we see regressions in our test suite or tool-eval, we may push additional commits that address them specifically.

**Comment by duckki** [comment]
The only remaining issue is `assert v.name` failure.
I just looked into the issue with Kevin. It appears that the upstream fixed try-returns variable initialization issue in their own way and we fixed it in our fork (commit `b6278d23447f6517e23cc59cbdb31adf8669da4f`). But, their changes have been erased during merging. We need to review what's lost. Probably we can adopt their fix of the `_parse_try_catch` function.

**Comment by duckki** [comment]
I'm running tool-eval 200.

**Comment by duckki** [comment]
200 looked as good as before. I force pushed my retouched commits.

**Pull request merged**
